import {
  ShieldCheck,
  TrendingUp,
  Target,
} from "lucide-react";

import AiHero from "../components/AiHero/AiHero";
import AiSummary from "../components/AiSummary/AiSummary";
import AiInsightCard from "../components/AiInsightCard/AiInsightCard";
import AiMotivationCard from "../components/AiMotivationCard/AiMotivationCard";

import DashboardCard from "@/features/dashboard/components/shared/DashboardCard";
import DashboardSection from "@/features/dashboard/components/shared/DashboardSection";

import { useAiAdvice } from "../hooks/useAiAdvice";

const AiPage = () => {
  const advice = useAiAdvice();

  if (advice.isLoading) {
    return (
      <div className="flex h-96 items-center justify-center">
        <p className="text-slate-500">
          Generating your AI financial report...
        </p>
      </div>
    );
  }

  if (advice.isError) {
    return (
      <div className="flex h-96 items-center justify-center">
        <p className="text-red-500">
          Failed to generate AI report.
        </p>
      </div>
    );
  }

  if (!advice.data) {
    return null;
  }

  return (
    <div className="space-y-8">
      {/* Hero */}
      <AiHero />

      {/* Financial Summary */}
      <DashboardSection
        title="Financial Overview"
        description="A personalized financial summary generated by FinPilot AI."
      >
        <DashboardCard>
          <AiSummary
            summary={advice.data.summary}
          />
        </DashboardCard>
      </DashboardSection>

      {/* Insights */}
      <div className="grid gap-6 lg:grid-cols-2">
        <DashboardCard>
          <AiInsightCard
            title="Strengths"
            subtitle="Your strongest financial habits."
            icon={ShieldCheck}
            iconBgColor="bg-emerald-100"
            iconColor="text-emerald-600"
            items={advice.data.strengths}
          />
        </DashboardCard>

        <DashboardCard>
          <AiInsightCard
            title="Improvements"
            subtitle="Areas that deserve attention."
            icon={TrendingUp}
            iconBgColor="bg-amber-100"
            iconColor="text-amber-600"
            items={advice.data.improvements}
          />
        </DashboardCard>
      </div>

      {/* Action Plan & Motivation */}
      <div className="grid gap-6 lg:grid-cols-2">
        <DashboardCard>
          <AiInsightCard
            title="Action Plan"
            subtitle="Recommended next financial steps."
            icon={Target}
            iconBgColor="bg-blue-100"
            iconColor="text-blue-600"
            items={advice.data.actionItems}
          />
        </DashboardCard>

        <DashboardCard>
          <AiMotivationCard
            motivation={advice.data.motivation}
          />
        </DashboardCard>
      </div>

      {/* AI Chat */}
      {/* <DashboardSection
        title="Ask FinPilot AI"
        description="Chat with your personal AI financial advisor."
      >
        <DashboardCard>
          <div className="flex h-96 items-center justify-center rounded-3xl border border-dashed border-slate-300 bg-slate-50">
            <p className="text-slate-400">
              AI Chat Coming Next...
            </p>
          </div>
        </DashboardCard>
      </DashboardSection> */}
    </div>
  );
};

export default AiPage;